name: Auto PR for Allowed Branches
description: Checks if current branch is allowed and creates PR if match.
inputs:
  allowed-branches:
    description: "Space separated list of allowed branch names"
    required: true
  pr-base-branch:
    description: "The base branch to merge into"
    required: true
  pr-title:
    description: "Title of the PR"
    required: true
  pr-body:
    description: "Body of the PR"
    required: true
  reviewers:
    description: "Comma-separated list of GitHub usernames to request review"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if branch is allowed and create PR
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        echo "Detected branch: $BRANCH_NAME"

        IFS=' ' read -r -a allowed <<< "${{ inputs.allowed-branches }}"

        is_allowed=false
        for allowed_branch in "${allowed[@]}"; do
          if [[ "$BRANCH_NAME" == "$allowed_branch" ]]; then
            is_allowed=true
            break
          fi
        done

        if [[ "$is_allowed" == "true" ]]; then
          echo "Branch $BRANCH_NAME is allowed. Creating PR..."

          REVIEWERS_OPTION=""
          if [[ -n "${{ inputs.reviewers }}" ]]; then
            IFS=',' read -r -a reviewers <<< "${{ inputs.reviewers }}"
            for reviewer in "${reviewers[@]}"; do
              REVIEWERS_OPTION+=" --reviewer=$reviewer"
            done
          fi

          gh pr create \
            --head="$BRANCH_NAME" \
            --base="${{ inputs.pr-base-branch }}" \
            --title="${{ inputs.pr-title }}" \
            --body="${{ inputs.pr-body }}" \
            $REVIEWERS_OPTION

        else
          echo "Branch $BRANCH_NAME is not in the allowed list. Skipping PR creation."
        fi
      shell: bash
