name: Deploy to GitHub Pages

author: Gabriel Montes

description: Deploy a directory to GitHub Pages

inputs:
  artifact-name:
    description: Base name for the artifact
    default: github-pages
  publish-dir:
    description: Directory to publish
    default: public

outputs:
  page_url:
    description: The URL of the deployed page
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        name: ${{ inputs.artifact-name }}-${{ github.run_id }}
        path: ${{ inputs.publish-dir }}
    - id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      with:
        artifact_name: ${{ inputs.artifact-name }}-${{ github.run_id }}

branding:
  color: orange
  icon: book-open
