# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: Setup Node

description: Setups up Node.js, restores NPM cache and installs dependencies

inputs:
  node-version:
    description: The version of Node to install.
    default: ""
  package-manager:
    description: The package manager to use (npm, pnpm).
    default: "npm"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      if: inputs.package-manager == 'pnpm'
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: ${{ inputs.package-manager == 'pnpm' && '**/pnpm-lock.yaml' || '**/package-lock.json' }}
        node-version: ${{ inputs.node-version }}
        node-version-file: .nvmrc
    - run: npm ci
      if: inputs.package-manager == 'npm'
      shell: bash
    - run: pnpm install --frozen-lockfile
      if: inputs.package-manager == 'pnpm'
      shell: bash
