# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: Setup Node

description: Setups up Node.js, restores NPM cache and installs dependencies

inputs:
  node-version:
    description: The version of Node to install.
    default: ""
  package-manager:
    description: The package manager to use (npm, pnpm).
    default: "npm"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      if: inputs.package-manager == 'pnpm'
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: ${{ inputs.package-manager == 'pnpm' && '**/pnpm-lock.yaml' || '**/package-lock.json' }}
        node-version: ${{ inputs.node-version }}
        node-version-file: .nvmrc
    - run: npm ci
      if: inputs.package-manager == 'npm'
      shell: bash
    - run: pnpm install --frozen-lockfile
      if: inputs.package-manager == 'pnpm'
      shell: bash
