# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: Setup Node

author: Gabriel Montes

description: Setups up Node, restores NPM cache and installs dependencies

inputs:
  cache:
    description: "Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm."
    default: npm
  node-version:
    description: The version of Node to install
    default: ""

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.0.0
      if: ${{ inputs.cache == 'pnpm' }}
    - uses: actions/setup-node@v4
      with:
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache == 'npm' && '**/package-lock.json' || '' }}
        node-version: ${{ inputs.node_version }}
        node-version-file: .nvmrc
    - run: npm ci
      shell: bash
      if: ${{ inputs.cache == 'npm' }}
    - run: pnpm install --frozen-lockfile
      shell: bash
      if: ${{ inputs.cache == 'pnpm' }}
    - run: yarn install --immutable
      shell: bash
      if: ${{ inputs.cache == 'yarn' }}

branding:
  color: blue
  icon: code
