# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: "Deploy"
on:
  workflow_call:
    inputs:
      namespace:
        description: "Kubernetes namespace (changed with 'kustomize set namespace')"
        type: string
        required: true
      kustomize:
        description: "Kustomize directory to apply"
        type: string
        required: true
      image:
        description: "Docker image(s) to deploy (changed with 'kustomize set image', separated by whitespace)"
        type: string
        required: true
      environment-name:
        description: "GitHub Deployment environment name"
        type: string
      environment-url:
        description: "GitHub Deployment environment URL"
        type: string
      preapply:
        description: "Commands to execute before applying"
        type: string
    secrets:
      KUBECONFIG:
        description: "Kubeconfig file contents"
        required: true
      KUBECONFIG_CONTEXT:
        description: "The name of the kubectl context to use"
        required: true

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    environment:
      name: "${{ inputs.environment-name }}"
      url: "${{ inputs.environment-url }}"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install kubectl"
        uses: azure/k8s-set-context@212a19233d93f03eceaac31ae5a1d1acf650b6ef # v4.0.1
        with:
          method: "kubeconfig"
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          context: "${{ secrets.KUBECONFIG_CONTEXT }}"

      - name: "Install Kustomize"
        uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0

      - name: "Pre-apply"
        if: inputs.preapply != ''
        working-directory: "${{ inputs.kustomize }}"
        run: "${{ inputs.preapply }}"

      - name: "Apply Kubernetes manifests"
        working-directory: "${{ inputs.kustomize }}"
        env:
          NAMESPACE: "${{ inputs.namespace }}"
          IMAGE: "${{ inputs.image }}"
        run: |
          kustomize edit set namespace "$NAMESPACE"
          for image in $IMAGE; do
            kustomize edit set image "$image"
          done
          kustomize build .
          kubectl apply -k .
