# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: "Deploy"
on:
  workflow_call:
    inputs:
      secret-name:
        description: "Kubernetes secret name"
        type: string
        default: "dockerhub"
      namespace:
        description: "Kubernetes namespace in which to create the secret"
        type: string
        required: true
      docker-server:
        description: "Docker registry server"
        type: string
        default: "https://index.docker.io/v1/"
    secrets:
      KUBECONFIG:
        description: "Kubeconfig file contents"
        required: true
      KUBECONFIG_CONTEXT:
        description: "The name of the kubectl context to use"
        required: true
      DOCKER_USERNAME:
        description: "Username for Docker registry authentication"
        required: true
      DOCKER_EMAIL:
        description: "Email for Docker registry"
        required: true
      DOCKER_PASSWORD:
        description: "Password for Docker registry authentication"
        required: true

jobs:
  registry-secret:
    name: "Registry secret"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install kubectl"
        uses: azure/k8s-set-context@212a19233d93f03eceaac31ae5a1d1acf650b6ef # v4.0.1
        with:
          method: "kubeconfig"
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          context: "${{ secrets.KUBECONFIG_CONTEXT }}"

      - name: "Create docker-registry secret"
        working-directory: "${{ inputs.kustomize }}"
        env:
          SECRET_NAME: "${{ inputs.secret-name }}"
          NAMESPACE: "${{ inputs.namespace }}"
          DOCKER_SERVER: "${{ inputs.docker-server }}"
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
          DOCKER_EMAIL: "${{ secrets.DOCKER_EMAIL }}"
        run: |
          # Create Docker Hub secret
          if ! kubectl get secret "$SECRET_NAME" --namespace="$NAMESPACE" > /dev/null; then
            echo "Creating Docker registry secret..."
            kubectl create secret docker-registry "$SECRET_NAME" \
              --docker-server="$DOCKER_SERVER" \
              --docker-username="$DOCKER_USERNAME" \
              --docker-password="$DOCKER_PASSWORD" \
              --docker-email="$DOCKER_EMAIL" \
              --namespace="$NAMESPACE"
          fi
